---
language: node_js
node_js:
  - "4.5.0"
  - "10"

sudo: false

cache:
  directories:
    - node_modules

matrix:
  fast_finish: true

before_install: if [[ `npm -v` != 3* ]]; then npm i -g npm@3; fi

install:
  - npm install

script:
  - npm test
